# Generated by Django 5.2.6 on 2025-09-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk_label', models.CharField(max_length=50)),
                ('risk_score', models.FloatField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('screen_time_hrs', models.FloatField()),
                ('night_usage_hrs', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('app_social_hrs', models.FloatField()),
                ('app_entertainment_hrs', models.FloatField()),
                ('app_education_hrs', models.FloatField()),
                ('late_sleep_flag', models.BooleanField(default=False)),
                ('low_sleep_flag', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'date'], name='students_da_student_e13cfd_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
