# Generated by Django 5.2.6 on 2025-10-17 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_addictionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('detected_words', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_alerts', to='students.student')),
            ],
        ),
    ]
